import Oval from "../image/Oval.png";
import ChizburgerMax from "../image/chizburger.png";
import LavashMax from "../image/lavash max.png";
export const cardItemInfo = [
  {
    id: 1,
    url: Oval,
    title: "Lavash mini",
    category: "Lavash",
    price: "18,000 UZS",
    additionalInfo: "Kichkina lavash, bla bla",
  },
  {
    id: 2,
    url: ChizburgerMax,
    title: "ChizburgerMax",
    category: "Burger",
    price: "23,000 UZS",
    additionalInfo: "Kichkina lavash, bla bla",
  },
  {
    id: 3,
    url: LavashMax,
    title: "Lavash Max",
    category: "Lavash",
    price: "18,000 UZS",
    additionalInfo: "Kichkina lavash, bla bla",
  },
  {
    id: 4,
    url: Oval,
    title: "Lavash S Sirom",
    category: "Lavash",
    price: "21,000 UZS",
    additionalInfo: "Kichkina lavash, bla bla",
  },
  {
    id: 5,
    url: ChizburgerMax,
    title: "Burger mini",
    category: "Burger",
    price: "11,000 UZS",
    additionalInfo: "Kichkina lavash, bla bla",
  },
  {
    id: 6,
    url: LavashMax,
    title: "Lavash mini",
    category: "Lavash",
    price: "18,000 UZS",
    additionalInfo: "Kichkina lavash, bla bla",
  },
  {
    id: 7,
    url: Oval,
    title: "Coca-Cola 1,5",
    category: "Ichimlik",
    price: "34,000 UZS",
    additionalInfo: "Kichkina lavash, bla bla",
  },
  {
    id: 8,
    url: ChizburgerMax,
    title: "Coca-Cola 1",
    category: "Ichimlik",
    price: "18,000 UZS",
    additionalInfo: "Kichkina lavash, bla bla",
  },
  {
    id: 9,
    url: LavashMax,
    title: "Burger mini",
    category: "Burger",
    price: "11,000 UZS",
    additionalInfo: "Kichkina lavash, bla bla",
  },
  {
    id: 10,
    url: Oval,
    title: "Lavash mini",
    category: "Lavash",
    price: "18,000 UZS",
    additionalInfo: "Kichkina lavash, bla bla",
  },
];
